---
- name: install fish shell
  package: 
    name: fish 
    state: head

- name: set fish as one of bashes
  command: "echo '/usr/local/bin/fish' | sudo tee -a /etc/shells"
  become: true

- name: Set fish as default shell
  user: name={{ user }} shell=/usr/local/bin/fish
