---
- name: set zsh prompt configurations
  template:
    src: up.j2
    dest: "/usr/local/bin/up"
    mode: 'u=rx,g=x,o=x'
  tags: 
    - update

- name: default key bindings 
  template:
    src: default_key_binding.j2
    dest: "{{ ansible_env.HOME }}/Library/KeyBindings/DefaultKeyBinding.dict"
    mode: 'u=rw,g=r,o=r'
  tags: 
    - update
