---
- name: install fish shell
  package:
    name: fish
    state: installed

- name: get fish location
  shell: which fish
  register: fish_location

- name: Set fish as default shell
  user: name={{ user }} shell={{ fish_location.stdout }}
