---
- name: install zsh shell
  package:
    name: zsh
    state: installed

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: clone zsh-autosuggestions
  git:
    repo: git://github.com/zsh-users/zsh-autosuggestions 
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: set zsh prompt configurations
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
  tags: 
    - update

