---
- name: install fish shell
  package:
    name: zsh
    state: installed

- name: get fish location
  shell: which fish
  register: fish_location

- name: Set fish as default shell
  user: name={{ user }} shell=/bin/zsh

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: clone zsh-autosuggestions
  git:
    repo: git://github.com/zsh-users/zsh-autosuggestions 
    dest: "{{ ansible_env.HOME }}.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: set fish prompt configurations
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
  tags: 
    - update

