---
- name: install user apps
  homebrew_cask: name={{ item }}
  with_items:
    - alfred
    - firefox
    - dropbox
    - java
    - caffeine
    - spectacle
    - skype
    - gimp
    - adium
    - limechat
  tags:
    - update

- name: install apps
  homebrew: name={{ item }}
  with_items:
    - tmux
    - fasd
    - ansible
    - git
    - git-extras
    - cmake
    - python
    - python3
    - leiningen # Clojure
    - rbenv
    - httpie
  tags:
    - update

- name: install libs
  homebrew: name={{ item }}
  with_items:
    - libmagic  # image magic
    - libxml2
    - libyaml
    - openssl
  tags:
    - update
