---
- name: install user apps
  homebrew_cask: name={{ item }}
  with_items:
    - alfred
    - firefox
    - dropbox
    - java
    - caffeine
    - spectacle
    - skype
    - iterm2
    - spotify
    - virtualbox

- name: install apps
  homebrew: name={{ item }}
  with_items:
    - vim
    - tmux
    - ansible
    - git
    - git-extras
    - cmake
    - python
    - python3
    - direnv # http://direnv.net/
    - htop
    - reattach-to-user-namespace
    - jq # json tool
    - gnu-sed 
    - markdown 
    - exa
    - httpie
    - asdf # https://github.com/asdf-vm/asdf
  tags: 
    - update

- name: install libs
  homebrew: name={{ item }}
  with_items:
    - libmagic  # image magic
    - libxml2
    - libyaml
    - openssl
    - coreutils
    - automake 
    - autoconf 
    - openssl
    - libyaml
    - readline 
    - libxslt 
    - libtool 
    - unixodbc
  tags: 
    - update
