---
- name: install user apps
  homebrew_cask: name={{ item }}
  with_items:
    - alfred
    - firefox
    - dropbox
    - javai
    - caffeine
    - spetacle
    - skype
    - gimp
    - adium
  tags:
    - update

- name: install apps
  homebrew: name={{ item }}
  with_items:
    - tmux
    - fasd
    - ansible
    - git
    - git-extras
    - cmake
    - python
    - python3
  tags:
    - update

