---
- name: tap homebrew
  homebrew_tap:
    name: neovim/neovim
    state: present

- name: install nvim
  package: 
    name: neovim
    state: installed

- name: install ack
  homebrew: name=ack

- name: set swap directory
  file: 
    path: "{{ ansible_env.HOME }}/.vim/swapfiles"
    state: directory
    mode: 0755

- name: install Vundle pkg dependency
  git: 
    repo: git@github.com:VundleVim/Vundle.vim.git 
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: make nvim config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    
- name: set vim configurations
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
  tags: 
    - update

- name: install python dependency
  shell: pip install neovim 

- name: install vundle dependencies
  shell: nvim +PluginInstall +PluginClean +qall
  tags:
     - update

- name: install cmake
  homebrew: name=cmake state=latest
