---
- name: install vim
  package: 
    name: vim
    state: installed

- name: set swap directory
  file: 
    path: "{{ ansible_env.HOME }}/.vim/swapfiles"
    state: directory
    mode: 0755

- name: install Vundle pkg dependency
  git: 
    repo: git@github.com:VundleVim/Vundle.vim.git 
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: set vim configurations
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
  tags: 
    - update

- name: install vundle dependencies
  shell: vim +PluginInstall +PluginClean +qall
  tags:
     - update

- name: install cmake
  homebrew: name=cmake state=latest
 
- name: install YouCompleteMe
  shell: "{{ ansible_env.HOME }}/.vim/bundle/youcompleteme/install.py --clang-completer"
