---
- name: install vim
  package: 
    name: vim
    state: head
 
- name: install Vundle pkg dependency
  git: 
    repo: git@github.com:VundleVim/Vundle.vim.git 
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: set vim configurations
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: install vundle dependencies
  shell: vim +PluginInstall +PluginClean +qall
