---
- name: install ack
  homebrew: name=ack

- name: set swap directory
  file: 
    path: "{{ ansible_env.HOME }}/.vim/swapfiles"
    state: directory
    mode: 0755

- name: install Vundle pkg dependency
  git: 
    repo: git@github.com:VundleVim/Vundle.vim.git 
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
    
- name: set vim configurations
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
  tags: 
    - update

- name: install vundle dependencies
  shell: vim +PluginInstall +qall
